### ISSUE TITLE
chore: re-seed storyboard known-failures ledger after #2182 (post-merge, measured)

### ISSUE THREAD

**Issue by numarasSigmaSoftware** [adcontextprotocol/salesagent#2209]
## Why

`tests/storyboard/known_failures.txt` and `EXPECTED_LEDGER` in `tests/unit/test_storyboard_ledger_state.py` are a **measured** snapshot of a specific in-network conformance run that PREDATES the #2182 MCP version-envelope fix (run 32478296091, head_sha 0ec6637dd, 2026-08-21). The snapshot attributes a large block of `mcp::` failures to `VALIDATION_ERROR: Unexpected keyword argument` / #1512 — "the capability probe (get_adcp_capabilities) is itself rejected, so most storyboards never reach their assertions."

Once #2182 merges, that cause no longer applies: the MCP capability probe SUCCEEDS, so those storyboards now reach their assertions and fail (or pass) for different, real reasons. In particular the version-negotiation / error-compliance storyboards (`unsupported_major_version`, `unsupported_release_version`) will return SUCCESS where they require `VERSION_UNSUPPORTED` — because #2182 is request-tolerance only and cross-major negotiation is deferred to #2181.

## What to do (post-merge, not before)

The ledger's own contract is "Measured, not derived," so this is a **re-seed from a real post-#2182 in-network run**, not a hand-edit. After #2182 merges:

1. Run the in-network storyboard conformance job on the merged tree (with `STORYBOARD_COMPLIANCE_DIR` / `STORYBOARD_SCHEMA_ROOT` configured — grading no-ops to a skip when they're unset).
2. Re-seed `known_failures.txt` + `EXPECTED_LEDGER` from that run: entries that now PASS graduate out; entries that now fail for a new reason get re-attributed to it (version-negotiation → #2181, not #1512).
3. Update the `#1512 (adcp_version rejected)` / "capability probe is REJECTED" narrative in the file header, the RFC-9421 (#1291) block, and `docs/test-obligations/storyboard-issue-map.yaml`'s `version-negotiation.yaml` note.

## Note

This does not affect normal CI: the ledger entries load `xfail(strict=False)` and the grading is skipped without the bundle env, so nothing reddens on the pre-fix snapshot. This is attribution accuracy for the conformance ledger, correctly produced from a measurement rather than by hand — which is why it must NOT be hand-edited into the pre-fix snapshot now.

Refs #1512, #2182, #2181, #1291.

**Comment by numarasSigmaSoftware** [comment]
Add-on for the re-seed: when this issue edits `tests/storyboard/known_failures.txt`, also add a one-line forward-note to the file header so a reader of the stale snapshot isn't misled, e.g.:

```
# NOTE (post-#2182): the mcp:: entries below record 'VALIDATION_ERROR: Unexpected keyword argument' (#1512) as the cause; #2182 removed that cause on MCP. These are superseded and re-seeded from a measured post-merge run per #2209.
```

Recorded here rather than on #2182 (its branch intentionally does not touch the ledger — F1/KM-3a are deferred to #2181/here) and not raced onto the in-flight #1546 ledger worktree. The header note lands naturally with the re-seed edit this issue already owns.
